// Copy, sample pages and demo configuration for the IndicDocParser page.
//
// The live demo runs on typeset facsimile pages rather than photographs: the
// page text is real DOM, so the detection overlay can be measured from the
// rendered blocks and stays aligned at every screen size. Each block carries
// what the *page* shows (`display`) and what the *model* emits (`md`) — the
// gap between the two is the point of the demo (unicode math on the page,
// LaTeX in the output; a drawn grid on the page, an HTML table in the output).

// Set this to your inference endpoint to run uploads through the real model.
// It should accept a multipart POST (field `file`) and answer with
// { blocks: [{ order, label, bbox: {x, y, w, h} normalised 0..1, markdown }] }.
export const DOC_PARSER_API_URL = '';

// Facsimile design space. Every box below is in these units; the renderer maps
// them to percentages, so the page scales without the overlay drifting.
export const PAGE_W = 1000;
export const PAGE_H = 1414;

export const HERO_STATS = [
    { value: 22, suffix: ' + EN', label: 'Languages' },
    { value: 37, suffix: '', label: 'Layout labels' },
    { value: 33, suffix: 'M + 0.8B', label: 'Parameters' },
    { value: 2, suffix: ' stages', label: 'Detect, then read' },
];

export const PIPELINE = [
    {
        id: 'page',
        step: '01',
        title: 'A page arrives',
        detail: 'A phone photo, a flatbed scan, a PDF render — printed or handwritten, skewed or clean.',
        tone: 'saffron',
    },
    {
        id: 'layout',
        step: '02',
        title: 'Layout is detected',
        detail: 'A 33M detector marks every region against 37 labels — paragraph, equation, table, figure, marginalia, page number.',
        tone: 'sky',
    },
    {
        id: 'order',
        step: '03',
        title: 'Reading order is resolved',
        detail: 'Columns, insets and footnotes are threaded into the sequence a human reader would follow.',
        tone: 'violet',
    },
    {
        id: 'read',
        step: '04',
        title: 'Each block is read',
        detail: 'A 0.8B recogniser transcribes block by block — Markdown for prose, LaTeX for maths, HTML for tables.',
        tone: 'teal',
    },
];

export const CAPABILITIES = [
    {
        id: 'scripts',
        icon: 'languages',
        title: '22 languages, 13 scripts',
        detail: 'Every Eighth Schedule language plus English, including Nastaliq and Ol Chiki.',
    },
    {
        id: 'hand',
        icon: 'pen',
        title: 'Handwriting, not just print',
        detail: 'Ruled worksheets, manuscript pages and margin notes — the same model, no separate checkpoint.',
    },
    {
        id: 'math',
        icon: 'sigma',
        title: 'Maths as LaTeX',
        detail: 'Fractions, integrals, matrices and multi-line derivations come back as compilable TeX.',
    },
    {
        id: 'tables',
        icon: 'table',
        title: 'Tables as HTML',
        detail: 'Merged cells and header rows survive, so a table stays queryable instead of becoming prose.',
    },
    {
        id: 'order',
        icon: 'order',
        title: 'Reading order that holds',
        detail: 'Two-column journals, boxed asides and footnotes are threaded in the order they are meant to be read.',
    },
    {
        id: 'grounded',
        icon: 'target',
        title: 'Every block is grounded',
        detail: 'Output carries the bounding box and label it came from, so a claim can always be traced to the page.',
    },
];

// Label palette. `tone` maps to a CSS custom property on .idp-page.
export const LABELS = {
    Title: { tone: 'violet', short: 'Title' },
    Heading: { tone: 'violet', short: 'Heading' },
    Paragraph: { tone: 'sky', short: 'Paragraph' },
    Equation: { tone: 'magenta', short: 'Equation' },
    Table: { tone: 'teal', short: 'Table' },
    Caption: { tone: 'amber', short: 'Caption' },
    Question: { tone: 'saffron', short: 'Question' },
    Answer: { tone: 'green', short: 'Answer' },
    'Page-number': { tone: 'slate', short: 'Page no.' },
};

export const OUTPUT_TABS = [
    { id: 'markdown', label: 'Markdown' },
    { id: 'rendered', label: 'Rendered' },
    { id: 'json', label: 'JSON' },
];

export const DEMO_PAGES = [
    {
        id: 'english-math',
        label: 'English',
        tag: 'Printed · dense mathematics',
        note: "Notebook page, printed facsimile",
        paper: 'print',
        lang: 'en',
        script: 'latin',
        blocks: [
            {
                order: 1,
                label: 'Page-number',
                box: { x: 872, y: 74, w: 78 },
                display: ['229'],
                md: '229',
                kind: 'text',
                conf: 0.99,
            },
            {
                order: 2,
                label: 'Paragraph',
                box: { x: 96, y: 156, w: 808 },
                display: [
                    'Thus we see that, if we can prove that twice the L.H.S. of (30) can be expanded in ascending powers of 1/n with integral coefficients, then the second part of (16) is at once proved.',
                ],
                md: 'Thus we see that, if we can prove that twice the L.H.S. of (30) can be expanded in ascending powers of $1/n$ with integral coefficients, then the second part of (16) is at once proved.',
                kind: 'text',
                conf: 0.97,
            },
            {
                order: 3,
                label: 'Paragraph',
                box: { x: 96, y: 320, w: 420 },
                display: ['Again from (27) we have'],
                md: 'Again from (27) we have',
                kind: 'text',
                conf: 0.99,
            },
            {
                order: 4,
                label: 'Equation',
                box: { x: 150, y: 392, w: 700 },
                display: ['d log Γ(n+1)  =  1 + 1⁄2 + 1⁄3 + 1⁄4 + … + 1⁄n − c', '      dμ'],
                md: '$$\\frac{d\\log \\Gamma(n+1)}{d\\mu} = 1 + \\frac{1}{2} + \\frac{1}{3} + \\frac{1}{4} + \\dots + \\frac{1}{n} - c$$',
                kind: 'latex',
                conf: 0.94,
            },
            {
                order: 5,
                label: 'Equation',
                box: { x: 150, y: 520, w: 700 },
                display: ['= log n + 1⁄2n − B₂⁄2n² + B₄⁄4n⁴ − B₆⁄6n⁶ + …    (31)'],
                md: '$$= \\log n + \\frac{1}{2n} - \\frac{B_2}{2n^2} + \\frac{B_4}{4n^4} - \\frac{B_6}{6n^6} + \\dots \\qquad (31)$$',
                kind: 'latex',
                conf: 0.92,
            },
            {
                order: 6,
                label: 'Paragraph',
                box: { x: 96, y: 620, w: 808 },
                display: ['where θ is a proper fraction ; and also by (25)'],
                md: 'where $\\theta$ is a proper fraction ; and also by (25)',
                kind: 'text',
                conf: 0.96,
            },
            {
                order: 7,
                label: 'Equation',
                box: { x: 180, y: 700, w: 640 },
                display: ['B₂ₚθ⁄2p·n²ᵖ  =  ∫₀^∞  2x²ᵖ⁻¹ ⁄ (1+x²)(e²π ⁿˣ − 1)  dx'],
                md: '$$\\frac{B_{2p}\\theta}{2p \\cdot n^{2p}} = \\int_0^{\\infty} \\frac{2x^{2p-1}}{(1+x^2)(e^{2\\pi nx}-1)}\\,dx$$',
                kind: 'latex',
                conf: 0.9,
            },
            {
                order: 8,
                label: 'Paragraph',
                box: { x: 96, y: 812, w: 808 },
                display: ['from which it can easily be shewn that'],
                md: 'from which it can easily be shewn that',
                kind: 'text',
                conf: 0.95,
            },
            {
                order: 9,
                label: 'Equation',
                box: { x: 150, y: 884, w: 700 },
                display: ['1⁄(n+2) − 1⁄(n+4) + 1⁄(n+6) − 1⁄(n+8) + 1⁄(n+10) − &c.'],
                md: '$$\\frac{1}{n+2} - \\frac{1}{n+4} + \\frac{1}{n+6} - \\frac{1}{n+8} + \\frac{1}{n+10} - \\&c.$$',
                kind: 'latex',
                conf: 0.93,
            },
            {
                order: 10,
                label: 'Equation',
                box: { x: 150, y: 984, w: 700 },
                display: ['= 1⁄2n − 2(2² − 1) B₂⁄2n² + 2⁸(2⁴ − 1) B₄⁄4n⁴    (32)'],
                md: '$$= \\frac{1}{2n} - 2(2^2-1)\\frac{B_2}{2n^2} + 2^8(2^4-1)\\frac{B_4}{4n^4} \\qquad (32)$$',
                kind: 'latex',
                conf: 0.91,
            },
            {
                order: 11,
                label: 'Paragraph',
                box: { x: 96, y: 1084, w: 808 },
                display: [
                    '13. The first few digits, and the number of digits in the integral part as well as in the numerator of Bₙ, can be found from the approximate formula :—',
                ],
                md: '13. The first few digits, and the number of digits in the integral part as well as in the numerator of $B_n$, can be found from the approximate formula :—',
                kind: 'text',
                conf: 0.96,
            },
            {
                order: 12,
                label: 'Equation',
                box: { x: 150, y: 1244, w: 700 },
                display: ['log₁₀ Bₙ = (n + 1⁄2) log₁₀ n − 1.2324743503 n + .700120    (33)'],
                md: '$$\\log_{10} B_n = (n + \\tfrac{1}{2})\\log_{10} n - 1.2324743503n + .700120 \\qquad (33)$$',
                kind: 'latex',
                conf: 0.94,
            },
        ],
    },

    {
        id: 'hindi-worksheet',
        label: 'हिन्दी',
        tag: 'Handwritten · ruled worksheet',
        note: 'Phone scan of a maths notebook',
        paper: 'ruled',
        lang: 'hi',
        script: 'deva',
        blocks: [
            {
                order: 1,
                label: 'Title',
                box: { x: 300, y: 120, w: 400 },
                display: ['प्रश्नावली 3.4'],
                md: '## प्रश्नावली 3.4',
                kind: 'heading',
                conf: 0.98,
            },
            {
                order: 2,
                label: 'Question',
                box: { x: 96, y: 236, w: 812 },
                display: ['27. निम्न समीकरण निकाय को विलोपन विधि से हल कीजिए।'],
                md: '**27.** निम्न समीकरण निकाय को विलोपन विधि से हल कीजिए।',
                kind: 'text',
                conf: 0.94,
            },
            {
                order: 3,
                label: 'Equation',
                box: { x: 160, y: 330, w: 690 },
                display: ['b²x + aby = 0    …(a)          a²x + aby = a³ + ab²    …(b)'],
                md: '$$b^2x + aby = 0 \\quad (a) \\qquad a^2x + aby = a^3 + ab^2 \\quad (b)$$',
                kind: 'latex',
                conf: 0.89,
            },
            {
                order: 4,
                label: 'Paragraph',
                box: { x: 96, y: 430, w: 620 },
                display: ['समी० (3) व (4) को जोड़ने पर,'],
                md: 'समी० (3) व (4) को जोड़ने पर,',
                kind: 'text',
                conf: 0.92,
            },
            {
                order: 5,
                label: 'Equation',
                box: { x: 200, y: 506, w: 600 },
                display: ['x(a² + b²) = a(a² + b²)', 'x = a'],
                md: '$$x(a^2+b^2) = a(a^2+b^2) \\\\ x = a$$',
                kind: 'latex',
                conf: 0.9,
            },
            {
                order: 6,
                label: 'Paragraph',
                box: { x: 96, y: 646, w: 700 },
                display: ['x का मान समी० (1) में रखने पर,'],
                md: 'x का मान समी० (1) में रखने पर,',
                kind: 'text',
                conf: 0.93,
            },
            {
                order: 7,
                label: 'Equation',
                box: { x: 200, y: 722, w: 600 },
                display: ['ab − ay = 0', 'y = ab⁄a  =  b'],
                md: '$$ab - ay = 0 \\\\ y = \\frac{ab}{a} = b$$',
                kind: 'latex',
                conf: 0.88,
            },
            {
                order: 8,
                label: 'Answer',
                box: { x: 96, y: 866, w: 500 },
                display: ['अतः  x = a,  y = b'],
                md: '**अतः** $x = a$, $y = b$',
                kind: 'text',
                conf: 0.95,
            },
            {
                order: 9,
                label: 'Question',
                box: { x: 96, y: 968, w: 812 },
                display: ['28. द्विघात समीकरण 2x² − 5x + 3 = 0 के मूल ज्ञात कीजिए।'],
                md: '**28.** द्विघात समीकरण $2x^2 - 5x + 3 = 0$ के मूल ज्ञात कीजिए।',
                kind: 'text',
                conf: 0.93,
            },
            {
                order: 10,
                label: 'Equation',
                box: { x: 200, y: 1062, w: 600 },
                display: ['2x² − 3x − 2x + 3 = 0', 'x(2x − 3) − 1(2x − 3) = 0', '(2x − 3)(x − 1) = 0'],
                md: '$$2x^2 - 3x - 2x + 3 = 0 \\\\ x(2x-3) - 1(2x-3) = 0 \\\\ (2x-3)(x-1) = 0$$',
                kind: 'latex',
                conf: 0.87,
            },
            {
                order: 11,
                label: 'Answer',
                box: { x: 96, y: 1256, w: 600 },
                display: ['अतः  x = 3⁄2  तथा  x = 1'],
                md: '**अतः** $x = \\tfrac{3}{2}$ तथा $x = 1$',
                kind: 'text',
                conf: 0.94,
            },
        ],
    },

    {
        id: 'telugu-novel',
        label: 'తెలుగు',
        tag: 'Handwritten · manuscript',
        note: 'A page from a handwritten novel',
        paper: 'manuscript',
        lang: 'te',
        script: 'telu',
        blocks: [
            {
                order: 1,
                label: 'Page-number',
                box: { x: 96, y: 84, w: 90 },
                display: ['199'],
                md: '199',
                kind: 'text',
                conf: 0.98,
            },
            {
                order: 2,
                label: 'Paragraph',
                box: { x: 110, y: 176, w: 790 },
                display: ['"ఎవరామె!" ప్రశ్నించాడు. ఆమెకున్న కళ్ళజోడు కొట్టవచ్చినట్టు దర్శనమిస్తుంది.'],
                md: '"ఎవరామె!" ప్రశ్నించాడు. ఆమెకున్న కళ్ళజోడు కొట్టవచ్చినట్టు దర్శనమిస్తుంది.',
                kind: 'text',
                conf: 0.9,
            },
            {
                order: 3,
                label: 'Paragraph',
                box: { x: 110, y: 322, w: 790 },
                display: ['"ఈమె పేరు సోనియా! వారెంట్‌ని వివాహమాడిన మూడు గంటల్లో విడాకులిచ్చింది," అన్నాడు యువరాజ్.'],
                md: '"ఈమె పేరు సోనియా! వారెంట్‌ని వివాహమాడిన మూడు గంటల్లో విడాకులిచ్చింది," అన్నాడు యువరాజ్.',
                kind: 'text',
                conf: 0.88,
            },
            {
                order: 4,
                label: 'Paragraph',
                box: { x: 110, y: 486, w: 560 },
                display: ['"ఎందుకు?" ఆశ్చర్యపోయాడు ధనార్జనరావు.'],
                md: '"ఎందుకు?" ఆశ్చర్యపోయాడు ధనార్జనరావు.',
                kind: 'text',
                conf: 0.93,
            },
            {
                order: 5,
                label: 'Paragraph',
                box: { x: 110, y: 606, w: 790 },
                display: ['"వారెంట్‌ని భారత పౌరుడిగా చేయడానికేనని అనుమానిస్తున్నాను," అంటూ వివరాలు చెప్పాడు యువరాజ్.'],
                md: '"వారెంట్‌ని భారత పౌరుడిగా చేయడానికేనని అనుమానిస్తున్నాను," అంటూ వివరాలు చెప్పాడు యువరాజ్.',
                kind: 'text',
                conf: 0.87,
            },
            {
                order: 6,
                label: 'Paragraph',
                box: { x: 110, y: 770, w: 700 },
                display: ['"నో, నో… ఐ నో నథింగ్!" అంటూ సోనియా గజగజ లాడిపోయింది.'],
                md: '"నో, నో… ఐ నో నథింగ్!" అంటూ సోనియా గజగజ లాడిపోయింది.',
                kind: 'text',
                conf: 0.86,
            },
            {
                order: 7,
                label: 'Paragraph',
                box: { x: 110, y: 912, w: 790 },
                display: ['"సూరిని గురించి మీరు తెలుసుకొన్న విషయాలేమిటి?" అడిగాడు యువరాజ్ బల్లముందున్న కుర్చీలో కూర్చుంటూ.'],
                md: '"సూరిని గురించి మీరు తెలుసుకొన్న విషయాలేమిటి?" అడిగాడు యువరాజ్ బల్లముందున్న కుర్చీలో కూర్చుంటూ.',
                kind: 'text',
                conf: 0.85,
            },
            {
                order: 8,
                label: 'Paragraph',
                box: { x: 110, y: 1090, w: 620 },
                display: ['"విచిత్రంగా వుంది" ఆలోచనలో పడ్డాడు యువరాజ్.'],
                md: '"విచిత్రంగా వుంది" ఆలోచనలో పడ్డాడు యువరాజ్.',
                kind: 'text',
                conf: 0.91,
            },
            {
                order: 9,
                label: 'Paragraph',
                box: { x: 110, y: 1212, w: 620 },
                display: ['"ఇంతకీ ఈ గందరగోళమంతా ఏమిటి?"'],
                md: '"ఇంతకీ ఈ గందరగోళమంతా ఏమిటి?"',
                kind: 'text',
                conf: 0.92,
            },
        ],
    },

    {
        id: 'report-columns',
        label: 'Two-column',
        tag: 'Printed · columns, table, footnote',
        note: 'Where reading order actually earns its keep',
        paper: 'print',
        lang: 'en',
        script: 'latin',
        blocks: [
            {
                order: 1,
                label: 'Heading',
                box: { x: 96, y: 110, w: 812 },
                display: ['3.2   Coverage across scripts'],
                md: '## 3.2 Coverage across scripts',
                kind: 'heading',
                conf: 0.99,
            },
            {
                order: 2,
                label: 'Paragraph',
                box: { x: 96, y: 210, w: 380 },
                display: [
                    'Annotation was spread deliberately rather than evenly. Scripts with the least existing digitised material were sampled hardest, so that coverage would not simply track what was already online.',
                ],
                md: 'Annotation was spread deliberately rather than evenly. Scripts with the least existing digitised material were sampled hardest, so that coverage would not simply track what was already online.',
                kind: 'text',
                conf: 0.97,
            },
            {
                order: 3,
                label: 'Paragraph',
                box: { x: 96, y: 430, w: 380 },
                display: [
                    'Roughly a third of every script’s allocation was reserved for handwriting, and a further tenth for pages photographed at an angle.',
                ],
                md: 'Roughly a third of every script’s allocation was reserved for handwriting, and a further tenth for pages photographed at an angle.',
                kind: 'text',
                conf: 0.96,
            },
            {
                order: 4,
                label: 'Paragraph',
                box: { x: 524, y: 210, w: 380 },
                display: [
                    'The table below reports pages accepted after adjudication. Pages rejected at review — cropped text, unreadable margins, duplicate scans — are excluded from every figure.',
                ],
                md: 'The table below reports pages accepted after adjudication. Pages rejected at review — cropped text, unreadable margins, duplicate scans — are excluded from every figure.',
                kind: 'text',
                conf: 0.97,
            },
            {
                order: 5,
                label: 'Paragraph',
                box: { x: 524, y: 430, w: 380 },
                display: [
                    'Devanagari carries four languages, which is why its total sits well above the rest of the set.',
                ],
                md: 'Devanagari carries four languages, which is why its total sits well above the rest of the set.',
                kind: 'text',
                conf: 0.98,
            },
            {
                order: 6,
                label: 'Table',
                box: { x: 96, y: 640, w: 808 },
                display: [],
                table: {
                    head: ['Script', 'Printed', 'Handwritten', 'Total'],
                    rows: [
                        ['Devanagari', '48,200', '19,400', '67,600'],
                        ['Bengali', '21,750', '9,100', '30,850'],
                        ['Telugu', '18,300', '8,650', '26,950'],
                        ['Tamil', '17,900', '7,200', '25,100'],
                        ['Nastaliq', '6,400', '4,850', '11,250'],
                    ],
                },
                md: '<table>\n  <thead>\n    <tr><th>Script</th><th>Printed</th><th>Handwritten</th><th>Total</th></tr>\n  </thead>\n  <tbody>\n    <tr><td>Devanagari</td><td>48,200</td><td>19,400</td><td>67,600</td></tr>\n    <tr><td>Bengali</td><td>21,750</td><td>9,100</td><td>30,850</td></tr>\n    <tr><td>Telugu</td><td>18,300</td><td>8,650</td><td>26,950</td></tr>\n    <tr><td>Tamil</td><td>17,900</td><td>7,200</td><td>25,100</td></tr>\n    <tr><td>Nastaliq</td><td>6,400</td><td>4,850</td><td>11,250</td></tr>\n  </tbody>\n</table>',
                kind: 'table',
                conf: 0.95,
            },
            {
                order: 7,
                label: 'Caption',
                box: { x: 96, y: 1052, w: 808 },
                display: ['Table 3.1 — Pages accepted after adjudication, by script and provenance.'],
                md: '*Table 3.1 — Pages accepted after adjudication, by script and provenance.*',
                kind: 'text',
                conf: 0.96,
            },
            {
                order: 8,
                label: 'Paragraph',
                box: { x: 96, y: 1150, w: 808 },
                display: ['¹ Counts are pages, not lines; a page contributes once regardless of block count.'],
                md: '¹ Counts are pages, not lines; a page contributes once regardless of block count.',
                kind: 'text',
                conf: 0.94,
            },
            {
                order: 9,
                label: 'Page-number',
                box: { x: 460, y: 1290, w: 80 },
                display: ['41'],
                md: '41',
                kind: 'text',
                conf: 0.99,
            },
        ],
    },
];

export const getDemoPage = (id) => DEMO_PAGES.find((page) => page.id === id) ?? DEMO_PAGES[0];
