#!/usr/bin/env python3
"""Re-sync the Indic-Translate post from the standalone mt-blog app.

    python3 scripts/sync-indic-translate-post.py [path/to/mt-blog]

Copies mt-blog/src/{components,data,lib} and public/images verbatim into
src/features/research/indic-translate-post/ and public/images/, and rewrites
mt-blog/src/styles.css into post.css scoped under `.mt-post`:

  * the `design.css` import is dropped (it is generated from this site's own
    globals.css, which is already loaded);
  * `:root` and `body` rules become the wrapper's own (`& { ... }`);
  * the box-sizing reset is dropped (Tailwind's preflight covers it);
  * every `@keyframes` block, including ones nested inside `@media`, is hoisted
    to the top level, because a keyframes rule nested inside a style rule is
    invalid CSS and would be dropped by the bundler.

IndicTranslatePostPage.jsx mirrors mt-blog/src/App.jsx by hand; if App.jsx
changes, update the page too.
"""
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SITE = os.path.dirname(HERE)
SRC = os.path.abspath(sys.argv[1] if len(sys.argv) > 1 else os.path.join(SITE, '..', 'mt-blog'))
DEST = os.path.join(SITE, 'src', 'features', 'research', 'indic-translate-post')
UNUSED = {
    'components/GlyphField.jsx', 'components/GlyphScatter.jsx', 'components/glyphScatter.css',
    'components/glyphSampler.js', 'data/glyphCells.js', 'data/glyphWeights.js',
}


def copy_tree():
    for sub in ('components', 'data', 'lib'):
        target = os.path.join(DEST, sub)
        if os.path.exists(target):
            shutil.rmtree(target)
        shutil.copytree(os.path.join(SRC, 'src', sub), target)
    for rel in UNUSED:
        p = os.path.join(DEST, rel)
        if os.path.exists(p):
            os.remove(p)
    images = os.path.join(SRC, 'public', 'images')
    os.makedirs(os.path.join(SITE, 'public', 'images'), exist_ok=True)
    for f in os.listdir(images):
        shutil.copy(os.path.join(images, f), os.path.join(SITE, 'public', 'images', f))


def split_blocks(css):
    """Top-level blocks of a stylesheet, brace-matched."""
    blocks, depth, buf = [], 0, ''
    for ch in css:
        buf += ch
        if ch == '{':
            depth += 1
        elif ch == '}':
            depth -= 1
            if depth == 0:
                blocks.append(buf)
                buf = ''
    return blocks


def extract_keyframes(block):
    """Return (block without nested @keyframes, [keyframes blocks])."""
    out, found, i = '', [], 0
    while True:
        j = block.find('@keyframes', i)
        if j == -1:
            out += block[i:]
            break
        k = block.find('{', j)
        depth, m = 0, k
        while True:
            if block[m] == '{':
                depth += 1
            elif block[m] == '}':
                depth -= 1
                if depth == 0:
                    break
            m += 1
        found.append(block[j:m + 1])
        out += block[i:j]
        i = m + 1
    return out, found


def scope_styles():
    css = open(os.path.join(SRC, 'src', 'styles.css')).read()
    css = css.replace("@import './design.css';", '')
    keyframes, scoped = [], []
    for block in split_blocks(css):
        head = block[:block.index('{')].strip()
        if head.startswith('@keyframes'):
            keyframes.append(block.strip())
            continue
        if head.startswith('*'):
            continue
        block, nested = extract_keyframes(block)
        keyframes.extend(b.strip() for b in nested)
        if head in (':root', 'body'):
            inner = block[block.index('{') + 1:block.rindex('}')]
            scoped.append('  & {' + inner + '}')
        else:
            scoped.append('  ' + block.strip().replace('\n', '\n  '))
    dedented = ['\n'.join(l[2:] if l.startswith('  ') else l for l in k.splitlines()) for k in keyframes]
    out = (
        "/* Indic-Translate post: the standalone page's stylesheet (mt-blog/src/styles.css),\n"
        "   scoped under .mt-post so its hero, token bridge and widget styles apply only on\n"
        "   this page. GENERATED by scripts/sync-indic-translate-post.py; do not hand-edit. */\n\n"
        + '\n\n'.join(dedented) + '\n\n.mt-post {\n' + '\n\n'.join(scoped) + '\n}\n'
    )
    open(os.path.join(DEST, 'post.css'), 'w').write(out)
    return len(keyframes), len(scoped)


if __name__ == '__main__':
    if not os.path.isdir(os.path.join(SRC, 'src')):
        sys.exit(f'no mt-blog source at {SRC}')
    copy_tree()
    kf, rules = scope_styles()
    print(f'synced from {SRC}: {rules} rules scoped, {kf} keyframes hoisted')
