// Page configuration for Indic-Speak.
//
// Ground rule, same as the Indic-Transcribe page: nothing here fabricates
// model output. Every clip under /examples/speak/ was generated by Indic-Speak
// from the script printed beside it (see speakScripts.js), every normalised
// reading is the text normaliser's real output, and the caption timings are
// paced from the clip clock and anchored to measured marks — never invented
// word alignments.
//
// Set VITE_SPEAK_API_URL to let the live demo synthesise text a visitor types.
// Until then the demo plays the pre-generated clip for the sample scripts and
// says plainly that an edited script needs an endpoint.

import {
    BOOK_ANCHORS,
    BOOK_BODY,
    BOOK_CLOSING,
    BOOK_OPENING,
    BOOK_TITLE,
    CODEMIX_HOOK,
    CODEMIX_SCRIPT,
    NEWS_HEADLINE_INDEX,
    NEWS_HEADLINE_SPAN,
    NEWS_PARAS,
    NEWS_TICKER,
    NORMALIZER_BEATS,
    PODCAST_SPEAKERS,
    PODCAST_TURNS,
    STORY_ANCHORS,
    STORY_BODY,
    STORY_CLOSING,
    STORY_OPENING,
    STORY_TITLE,
} from './speakScripts';
import { distribute } from './pacing';

export const SPEAK_API_URL = import.meta.env.VITE_SPEAK_API_URL ?? '';

const CLIP = '/examples/speak';
const ART = `${CLIP}/art`;

// Measured with ffprobe on the encoded files.
export const CLIP_LENGTHS = {
    hook: 4.949,
    codemix: 8.85,
    podcast: 26.85,
    news: 30.549,
    story: 144.813,
    book: 319.552,
    tutor: 13.739,
    normAc: 6.05,
    normFees: 9.489,
    normKyc: 15.5,
    normSoftmax: 8.405,
};

export const ACCENTS = {
    saffron: '#E0620D',
    sky: '#1F6FD1',
    teal: '#0C8C82',
    violet: '#5B44D4',
    amber: '#B8760A',
    green: '#159A50',
    magenta: '#CC1E74',
};

/* ------------------------------------------------------------------ hero */

export const HERO = {
    eyebrow: 'Introducing',
    wordmark: 'Indic-Speak',
    tagline: 'Speech, for the way we actually speak.',
    description:
        'A 4B-parameter text-to-speech model for 22 Indian languages and English. It holds a code-mixed sentence together, takes speaker tags for two-party audio, and narrates a whole chapter in one continuous pass.',
    hook: {
        audio: `${CLIP}/hook-codemix.mp3`,
        duration: CLIP_LENGTHS.hook,
        script: CODEMIX_HOOK,
        lang: 'hi',
        caption: 'Hindi + English · one voice, one pass',
    },
};

export const HERO_STATS = [
    { value: 23, label: 'Languages', hint: '22 Eighth Schedule languages + English' },
    { value: 4, suffix: 'B', label: 'Parameters', hint: 'Single checkpoint' },
    { value: 2, prefix: '', suffix: '+ min', label: 'Single pass', hint: 'Continuous narration, no stitching' },
    { value: 6, label: 'Styles below', hint: 'Every clip on this page is real output' },
];

/* -------------------------------------------------------------- overview */

export const OVERVIEW = {
    kicker: 'The model',
    title: 'We change how we speak for every role. A speech model should too.',
    body: [
        'Most text-to-speech is built for one clean sentence at a time, in one language at a time. That is not how anyone in India talks. A sentence starts in Marathi and lands on a Latin word; a fee is written ₹1,500 but said as one thousand five hundred; a PAN number has to be spelled out letter by letter; an equation has to be read, not skipped.',
        'Indic-Speak is one 4B-parameter checkpoint that handles all of that. Text goes through a normaliser that rewrites numbers, symbols, IDs and equations into the words a speaker would actually use — in the language of the sentence, not translated into English — and then into a voice that keeps its rhythm across a paragraph, a bulletin or a chapter.',
        'It was built with AI4Bharat for the places speech is load-bearing: a tutor explaining photosynthesis, a bulletin read the way All India Radio reads one, a storybook for a child who has no one free to read to them, an audiobook that runs for an hour without drifting.',
    ],
    specs: [
        { label: 'Languages', value: '22 + English' },
        { label: 'Parameters', value: '4B' },
        { label: 'Input', value: 'Plain text, LaTeX, speaker tags' },
        { label: 'Long-form', value: 'Chapters of any duration' },
        { label: 'Code-mixing', value: 'Any Indic language + English' },
        { label: 'Built with', value: 'AI4Bharat' },
    ],
};

// The film's tile mosaic, with the script each one is demonstrated in.
export const CAPABILITIES = [
    {
        id: 'codemix',
        title: 'Code-mixed speech',
        detail: 'Hinglish, Tanglish, Banglish. The Latin words keep their English pronunciation without the sentence losing its Indian rhythm.',
        glyph: 'अ',
        tone: 'sky',
        span: 'wide',
    },
    {
        id: 'podcast',
        title: 'Two-party podcasts',
        detail: 'Speaker tags in the prompt, two distinct voices out — turn-taking and all — from a single generation.',
        glyph: 'দ',
        tone: 'teal',
    },
    {
        id: 'news',
        title: 'News reading',
        detail: 'The formal register a bulletin needs, held steady from the sign-on to the handoff.',
        glyph: 'മ',
        tone: 'amber',
    },
    {
        id: 'story',
        title: "Children's stories",
        detail: 'Expressive reads with dialogue in character, at a rhythm a five-year-old can follow.',
        glyph: 'भो',
        tone: 'green',
        span: 'wide',
    },
    {
        id: 'book',
        title: 'Audiobooks',
        detail: 'Chapter-length narration in one continuous pass — no per-sentence stitching, no drift.',
        glyph: 'த',
        tone: 'magenta',
    },
    {
        id: 'stem',
        title: 'Numbers, IDs, equations',
        detail: 'A normaliser turns ₹1,500, AC-7XQ19 and a softmax into the words a teacher would say.',
        glyph: 'Σ',
        tone: 'violet',
    },
];

export const VOICE_ROLES = ['Storyteller', 'Teacher', 'Newsreader', 'Podcaster'];

/* ------------------------------------------------------------ live  demo */

// Each preset is a script that has actually been through the model, so the
// demo can answer with real audio even with no endpoint configured.
export const DEMO_PRESETS = [
    {
        id: 'hinglish',
        label: 'Hinglish · work message',
        language: 'Hindi + English',
        lang: 'hi',
        voice: 'Conversational',
        tone: 'sky',
        written: CODEMIX_SCRIPT,
        spoken: null,
        focus: [],
        audio: `${CLIP}/codemix-ship.mp3`,
        duration: CLIP_LENGTHS.codemix,
    },
    {
        id: 'tutor',
        label: 'Hindi · classroom explainer',
        language: 'Hindi + English',
        lang: 'hi',
        voice: 'Teacher',
        tone: 'violet',
        written:
            'चलो, photosynthesis यानी प्रकाश-संश्लेषण के बारे में पढ़ते हैं। पौधे, सूरज की रोशनी, पानी और CO₂ से अपना खाना खुद बनाते हैं — और बदले में हमें oxygen देते हैं.',
        spoken: null,
        focus: ['कार्बन', 'डाइऑक्साइड'],
        audio: `${CLIP}/tutor-photosynthesis-hi.mp3`,
        duration: CLIP_LENGTHS.tutor,
        note: 'CO₂ is read as कार्बन डाइऑक्साइड — in Hindi, not spelled out in English.',
    },
    {
        id: 'gujarati',
        label: 'Gujarati · model number',
        language: 'Gujarati',
        lang: 'gu',
        voice: 'Dhara',
        tone: 'amber',
        written: NORMALIZER_BEATS[0].written,
        spoken: NORMALIZER_BEATS[0].spoken,
        focus: NORMALIZER_BEATS[0].focus,
        audio: `${CLIP}/norm-ac-gujarati.mp3`,
        duration: CLIP_LENGTHS.normAc,
    },
    {
        id: 'bengali',
        label: 'Bengali · clinic fees',
        language: 'Bengali',
        lang: 'bn',
        voice: 'Ishita',
        tone: 'green',
        written: NORMALIZER_BEATS[1].written,
        spoken: NORMALIZER_BEATS[1].spoken,
        focus: NORMALIZER_BEATS[1].focus,
        audio: `${CLIP}/norm-fees-bengali.mp3`,
        duration: CLIP_LENGTHS.normFees,
    },
    {
        id: 'marathi',
        label: 'Marathi · PAN + Aadhaar',
        language: 'Marathi',
        lang: 'mr',
        voice: 'Anagha',
        tone: 'teal',
        written: NORMALIZER_BEATS[2].written,
        spoken: NORMALIZER_BEATS[2].spoken,
        focus: NORMALIZER_BEATS[2].focus,
        audio: `${CLIP}/norm-kyc-marathi.mp3`,
        duration: CLIP_LENGTHS.normKyc,
    },
    {
        id: 'softmax',
        label: 'English · softmax',
        language: 'English',
        lang: 'en',
        voice: 'Parth',
        tone: 'violet',
        written: NORMALIZER_BEATS[3].written,
        tex: NORMALIZER_BEATS[3].tex,
        spoken: NORMALIZER_BEATS[3].spoken,
        focus: NORMALIZER_BEATS[3].focus,
        audio: `${CLIP}/norm-softmax-english.mp3`,
        duration: CLIP_LENGTHS.normSoftmax,
    },
];

/* ---------------------------------------------------------- normalizer */

export const NORMALIZER = {
    kicker: 'The harness',
    words: ['Numbers.', 'Symbols.', 'Equations.', 'Across languages.'],
    title: 'Written one way, said another.',
    blurb:
        'A rupee amount, a model number, an Aadhaar, a softmax. Before a single sample is generated the text normaliser rewrites them into the words a speaker of that language would use. These four are its real output.',
    // `tokens` are the exact substrings of the written text that the
    // normaliser rewrote — the written-side counterpart to `focus`.
    beats: NORMALIZER_BEATS.map((beat, index) => ({
        ...beat,
        tokens: [
            ['AC-7XQ19'],
            ['\u20b91,500', '\u20b9650'],
            ['VQKRM5278N', '4268 9153 7042'],
            ['S(x)_i = e^{x_i} / \\sum_j e^{x_j}'],
        ][index],
        id: ['ac', 'fees', 'kyc', 'softmax'][index],
        audio: `${CLIP}/${['norm-ac-gujarati', 'norm-fees-bengali', 'norm-kyc-marathi', 'norm-softmax-english'][index]}.mp3`,
        duration: [
            CLIP_LENGTHS.normAc,
            CLIP_LENGTHS.normFees,
            CLIP_LENGTHS.normKyc,
            CLIP_LENGTHS.normSoftmax,
        ][index],
        lang: ['gu', 'bn', 'mr', 'en'][index],
        tone: ['amber', 'green', 'teal', 'violet'][index],
    })),
};

/* ------------------------------------------------------------- examples */

const podcastTurns = PODCAST_TURNS.map((turn, index) => ({
    ...turn,
    start: index === 0 ? 0 : PODCAST_TURNS[index - 1].end,
    speakerName: PODCAST_SPEAKERS[turn.speaker],
}));

// The bulletin, anchored on the one segment that was measured: the first
// headline runs 4.987s → 10.5s. The sign-on before it and the rest after it
// are paced inside the two remaining stretches.
const newsBlocks = (() => {
    const [headStart, headEnd] = NEWS_HEADLINE_SPAN;
    const before = NEWS_PARAS.slice(0, NEWS_HEADLINE_INDEX);
    const after = NEWS_PARAS.slice(NEWS_HEADLINE_INDEX + 1);

    return [
        ...distribute(before, 0, headStart).map((span, i) => ({ ...span, text: before[i] })),
        { start: headStart, end: headEnd, text: NEWS_PARAS[NEWS_HEADLINE_INDEX], kind: 'headline' },
        ...distribute(after, headEnd, CLIP_LENGTHS.news).map((span, i) => ({
            ...span,
            text: after[i],
        })),
    ];
})();

// Long reads: opening and closing sit on measured marks, the body is paced
// between them.
const longRead = (opening, body, closing, anchors, duration) => [
    { start: 0, end: anchors.openEnd, text: opening, kind: 'opening' },
    ...distribute(body, anchors.openEnd, anchors.closeStart).map((span, i) => ({
        ...span,
        text: body[i],
    })),
    { start: anchors.closeStart, end: duration, text: closing, kind: 'closing' },
];

export const EXAMPLES = [
    {
        id: 'codemix',
        tab: 'Code-mixed',
        kicker: 'Conversation',
        title: "Real speech doesn't stop at language boundaries.",
        blurb:
            'One sentence, two languages, one voice. The Latin words are said as English words; everything around them keeps its Hindi cadence.',
        meta: 'Hindi + English',
        tone: 'sky',
        layout: 'line',
        lang: 'hi',
        audio: `${CLIP}/codemix-ship.mp3`,
        duration: CLIP_LENGTHS.codemix,
        script: CODEMIX_SCRIPT,
        chips: ['Hinglish', 'Tanglish', 'Banglish', 'Any Indic language + English'],
    },
    {
        id: 'podcast',
        tab: 'Podcast',
        kicker: 'Two speakers',
        title: 'Two-party podcast, generated in one go.',
        blurb:
            'Speaker tags in the prompt do the turn-taking. This is a single generation — not two renders spliced together — on the Transformers paper, in Hindi and English.',
        meta: 'Hindi + English · 2 voices',
        tone: 'teal',
        layout: 'chat',
        lang: 'hi',
        audio: `${CLIP}/podcast-stem.mp3`,
        duration: CLIP_LENGTHS.podcast,
        speakers: PODCAST_SPEAKERS,
        turns: podcastTurns,
        chips: ['One generation', 'Speaker tags', 'Natural turn-taking'],
    },
    {
        id: 'news',
        tab: 'News',
        kicker: 'On air',
        title: 'A bulletin, read the way a bulletin is read.',
        blurb:
            'The All India Radio register: the sign-on, the headlines, the handoff — formal, even, and consistent from the first line to the last.',
        meta: 'Malayalam',
        tone: 'amber',
        layout: 'bulletin',
        lang: 'ml',
        audio: `${CLIP}/news-malayalam.mp3`,
        duration: CLIP_LENGTHS.news,
        blocks: newsBlocks,
        ticker: NEWS_TICKER,
        chips: ['Formal register', 'Consistent', 'Sign-on to handoff'],
    },
    {
        id: 'tutor',
        tab: 'Tutoring',
        kicker: 'Built for education',
        title: 'Photosynthesis, explained the way a teacher explains it.',
        blurb:
            'A patient read of a mixed Hindi–English explanation, with the chemistry said in Hindi rather than spelled out in English.',
        meta: 'Hindi + English',
        tone: 'violet',
        layout: 'tutor',
        lang: 'hi',
        audio: `${CLIP}/tutor-photosynthesis-hi.mp3`,
        duration: CLIP_LENGTHS.tutor,
        script: DEMO_PRESETS[1].written,
        focus: ['कार्बन', 'डाइऑक्साइड'],
        image: `${ART}/tutor-classroom.jpg`,
        chips: ['Tutor bots', 'Lesson audio', 'Read-aloud'],
    },
    {
        id: 'story',
        tab: 'Story',
        kicker: "Children's story",
        title: 'So that every child has a storyteller.',
        blurb:
            'Two and a half minutes of expressive reading in one pass, dialogue in character, at a rhythm a child can follow.',
        meta: 'Hindi · expressive read',
        tone: 'green',
        layout: 'page',
        lang: 'hi',
        audio: `${CLIP}/story-bholu-hi.mp3`,
        duration: CLIP_LENGTHS.story,
        titles: STORY_TITLE,
        art: `${ART}/reading-teacher.svg`,
        blocks: longRead(
            STORY_OPENING,
            STORY_BODY,
            STORY_CLOSING,
            STORY_ANCHORS,
            CLIP_LENGTHS.story
        ),
        chips: ['2:24 in one pass', 'Dialogue in character', 'Consistent rhythm'],
    },
    {
        id: 'book',
        tab: 'Audiobook',
        kicker: 'Long-form',
        title: 'Full audiobook chapters, of any duration.',
        blurb:
            'Chapter one of Ponniyin Selvan, paragraph after paragraph, five minutes of continuous narration with no stitching and no drift.',
        meta: 'Tamil · Kalki',
        tone: 'magenta',
        layout: 'page',
        lang: 'ta',
        audio: `${CLIP}/book-tamil-ponniyin.mp3`,
        duration: CLIP_LENGTHS.book,
        titles: BOOK_TITLE,
        art: `${ART}/kalki.svg`,
        blocks: longRead(BOOK_OPENING, BOOK_BODY, BOOK_CLOSING, BOOK_ANCHORS, CLIP_LENGTHS.book),
        chips: ['5:19 in one pass', 'Paragraph by paragraph', 'No stitching'],
    },
];

/* ------------------------------------------------------------- closing */

export const CLOSING = {
    kicker: 'Availability',
    title: 'One model, 23 languages.',
    blurb: 'Live and hosted on day one:',
    platforms: ['Bodhan', 'VoiceEra', 'Bhashini'],
    note: 'Early checkpoint — shared for integration testing. Voice quality is still moving.',
};
