import { useEffect } from 'react';
import { motion } from 'motion/react';
import Navbar from '../../home/components/Navbar';
import Footer from '../../home/components/Footer';

const sections = [
    {
        heading: '1. Acceptance of Terms',
        paragraphs: [
            'These Terms of Use (“Terms”) constitute a legally binding agreement between you (“User”, “you”) and IITM BODHAN-AI FOUNDATION, a company registered under Section 8 of the Companies Act, 2013, having its registered office at IIT Madras Research Park, E1-14, 1st Floor, Kanagam Rd, Taramani, Chennai–600113 (“Bodhan AI”, “we”, “us”, “our”), governing your access to and use of Bodhak, an AI tutoring chatbot, and any related websites, mobile applications, and services (collectively, the “Service”).',
            'By creating an account, accessing, or using the Service, you agree to be bound by these Terms and our Privacy Policy, which is incorporated herein by reference. If you do not agree, please do not use the Service.',
        ],
    },
    {
        heading: '2. Eligibility and Types of Users',
        paragraphs: [
            'The Service supports several categories of Users, each subject to the additional provisions below:',
        ],
        list: [
            'Students, including children under 18 years, who use the AI tutoring chatbot for practice sessions.',
            'Parents/Guardians, who may create linked accounts to consent on behalf of, and oversee, a child User (see Section 7).',
            'Teacher Users, who may access AI-literacy training content, student progress dashboards, and simulation-creation tools (see Sections 8 and 9).',
            'Institutional Users (schools/coaching centres), who onboard students and Teacher Users, typically under a separate institutional agreement with Bodhan AI in addition to these Terms.',
        ],
        trailingParagraphs: [
            'If you are under 18 years of age, you may use the Service only with the involvement, supervision, and consent of a parent or legal guardian, who agrees to be bound by these Terms on your behalf.',
            'Institutional Users that onboard students or Teacher Users represent that they have obtained all necessary consents and authorisations to do so.',
            'You agree to provide accurate, current, and complete information during registration and to keep your account credentials confidential. You are responsible for all activity that occurs under your account.',
            'We reserve the right to suspend or terminate accounts that provide false information or violate these Terms.',
        ],
    },
    {
        heading: '3. Description of the Service',
        paragraphs: [
            'Bodhan AI provides an AI-powered tutoring chatbot application that offers personalised learning support, practice questions, doubt-resolution, and progress tracking, using artificial intelligence and machine-learning technologies, including large language models (“AI Tutor”). The Service also offers AI-literacy modules and simulation-creation tools intended for Teacher Users.',
            'Important: The AI Tutor is an educational support tool and is not a substitute for a qualified teacher, tutor, or examiner. Responses generated by the AI Tutor may occasionally be incomplete, outdated, or inaccurate. Users should independently verify important academic information and are encouraged to consult a teacher for graded assessments or high-stakes academic decisions.',
        ],
    },
    {
        heading: '4. Subscription, Fees, and Payments',
        paragraphs: [
            '[If the Service is offered on a free/freemium/paid basis, describe applicable plans here, e.g.: Certain features of the Service may be offered free of charge, while others may require payment of a subscription fee as displayed at the time of purchase.]',
        ],
        list: [
            'All fees are payable in advance and are exclusive of applicable taxes unless stated otherwise.',
            'Payments are processed through third-party payment gateways or, where purchased via our mobile application, through the applicable app store’s in-app purchase system; we do not store your complete card or bank details.',
            'Refunds, if any, shall be governed by our separate Refund/Cancellation Policy, available at [URL].',
            'As a Section 8 company, any surplus generated from fees (if applicable) shall be applied solely towards the objects for which Bodhan AI is established, and not distributed as profit.',
            'Teacher Users are allocated a limited number of simulation-creation credits (see Section 9) as part of their access; credits are non-transferable and do not carry monetary value.',
        ],
    },
    {
        heading: '5. User Conduct',
        paragraphs: ['You agree not to:'],
        list: [
            'Use the Service for any unlawful purpose or in violation of any applicable law.',
            'Submit false, misleading, abusive, obscene, defamatory, or otherwise objectionable content.',
            'Attempt to gain unauthorised access to the Service, other users’ accounts (including another student’s Practice Sessions), or our systems.',
            'Use automated means (bots, scrapers) to access or extract data from the Service without our written consent.',
            'Use the AI Tutor to generate content that is harmful, discriminatory, or intended to facilitate academic dishonesty (e.g., generating answers for a live proctored examination in violation of the examination’s own rules).',
            'Reverse-engineer, decompile, or attempt to extract the underlying models, source code, or algorithms of the Service.',
            'Reproduce, resell, or commercially exploit any part of the Service, including AI-literacy training content or simulations, without our prior written consent.',
        ],
    },
    {
        heading: '6. Intellectual Property',
        paragraphs: [
            'All content, features, and functionality of the Service, including text, graphics, logos, software, AI-literacy training materials, and the underlying AI models and educational content curated or created by Bodhan AI (“Bodhan AI Content”), are owned by or licensed to Bodhan AI and are protected by applicable intellectual property laws.',
            'Subject to your compliance with these Terms, we grant you a limited, non-exclusive, non-transferable, revocable licence to access and use the Service for personal, non-commercial educational purposes (or, for Teacher Users, for professional-development purposes).',
        ],
        list: [
            'User Content: You retain ownership of content you submit to the Service (e.g., Practice Session questions, essays, images, or files). By submitting such content, you grant Bodhan AI a worldwide, royalty-free, non-exclusive licence to use, reproduce, and process it to provide, maintain, and improve the Service. This licence does not, by itself, include use of your content to train or develop AI/ML models — that use is governed separately by Section 10.',
            'AI-Generated Output: Responses generated by the AI Tutor in response to your queries may be used by you for personal educational purposes. Bodhan AI makes no representation regarding the originality, accuracy, or exclusivity of AI-generated output.',
            'Teacher-Created Simulations: Ownership of simulations created by Teacher Users is governed by Section 9, and not by the general User Content licence above.',
        ],
    },
    {
        heading: '7. Access to a Child User’s Practice Sessions',
        paragraphs: ['Where a User is a child, you acknowledge and agree that:'],
        list: [
            'A linked parent/guardian account, and (where the child is enrolled through an Institutional User) the child’s assigned Teacher User(s) and school administrators, may be able to view the child’s Practice Session content, transcripts, and/or performance data, as further described in our Privacy Policy.',
            'Such access is intended to enable academic oversight, support, and progress monitoring, and is disclosed to the child within the Service interface.',
            'A parent/guardian or Institutional User is responsible for determining the appropriate level of access for a given Teacher User, and may request changes to such access through the channels described in our Privacy Policy.',
            'Bodhan AI is not responsible for a parent/guardian’s, Teacher User’s, or Institutional User’s own use or handling of a child’s Practice Session data once accessed, beyond Bodhan AI’s own obligations as data fiduciary under applicable law.',
        ],
    },
    {
        heading: '8. Teacher and Educator Use of the Service',
        paragraphs: [
            'Where you register or are provisioned access as a Teacher User, the following apply in addition to the general Terms:',
        ],
        list: [
            'Access to AI-literacy training modules, dashboards, or student progress data is provided solely for legitimate educational and professional-development purposes connected to your role as an educator.',
            'You agree to access student Practice Session data only to the extent necessary for your teaching responsibilities, and not to share such data with any person not authorised to receive it.',
            'Where your access is provisioned by an Institutional User, that institution may configure, limit, or revoke your access to the Service at its discretion, and your continued access is subject to your relationship with that institution.',
            'Completion records, certificates, or credentials issued through AI-literacy modules are provided “as is” and do not constitute a formal degree, diploma, or statutory qualification unless expressly stated otherwise.',
        ],
    },
    {
        heading: '9. Teacher-Created Simulations',
        paragraphs: [
            'Where the Service permits Teacher Users to create interactive simulations for students (“Simulations”), the following apply:',
        ],
        list: [
            'Simulation-creation is limited by a credit allocation (currently five (5) to ten (10) credits per Teacher User, subject to change), intended to encourage focused, higher-quality submissions rather than high-volume output.',
            'Published Simulations may be reviewed and voted on by other Teacher Users to assess quality; Bodhan AI may use such votes to determine whether a Simulation remains published, is featured, or is removed, at its sole discretion.',
            'Bodhan AI is not liable for the outcome of any peer review or voting process, including a Teacher User’s dissatisfaction with a rating given to their Simulation by other Teacher Users.',
            'Ownership and Assignment: As between you and Bodhan AI, all right, title, and interest (including all intellectual property rights) in and to any Simulation you create using the Service is hereby irrevocably assigned to Bodhan AI, worldwide and in perpetuity, effective upon creation/submission of the Simulation, to the fullest extent permitted under the Copyright Act, 1957 and other applicable law. You agree to execute any further documents reasonably required by Bodhan AI to give effect to this assignment.',
            'You consent to Bodhan AI modifying, adapting, translating, or otherwise altering your Simulation without further reference to you, and agree not to assert any moral rights (including the right of attribution or integrity under Section 57 of the Copyright Act, 1957) against Bodhan AI in respect of such use, to the extent permitted by law.',
            'You represent that any Simulation you submit is your own original work (or that you hold all rights necessary to submit and assign it) and does not infringe the intellectual property or other rights of any third party.',
            'Simulation-creation tools and any resulting Simulations are provided for use within the Service; Teacher Users may not export, resell, or use Simulations outside the Service without Bodhan AI’s prior written consent.',
        ],
    },
    {
        heading: '10. Use of Data for AI Model Development',
        paragraphs: [
            'From time to time, Bodhan AI may wish to use content submitted through the Service — including student voice recordings, text prompts, uploaded images, and other files (“Training Data”) — to develop, train, test, or improve Bodhan AI’s own AI/ML models. This use is separate from, and in addition to, the general User Content licence in Section 6, and is governed as follows:',
        ],
        list: [
            'Opt-in required: Training Data will be used for model development only where the applicable User (or, for a child User, their parent/guardian) has given specific, informed, affirmative consent to that use, separately from acceptance of these Terms and separately from consent to use of the Service itself, as described in our Privacy Policy.',
            'No use of a child’s voice, text, images, or files as Training Data will occur without such prior verifiable parental/guardian consent; general acceptance of these Terms by a parent/guardian does not, by itself, constitute this consent.',
            'Withdrawal: a User (or parent/guardian) who has consented to their (or their child’s) data being used as Training Data may withdraw that consent at any time by writing to support@bodhan.ai, after which Bodhan AI will stop using that User’s future submissions as Training Data going forward; withdrawal does not require or entail deletion of any model already trained using data submitted prior to withdrawal, except where required by applicable law or separately requested under the data-deletion rights in our Privacy Policy.',
            'Where feasible, Bodhan AI will use Training Data in de-identified or aggregated form for model development, and will not use Training Data to build a profile of, or targeted output specific to, an individual child.',
            'This Section 10 does not restrict Bodhan AI’s use of anonymised or aggregated usage analytics (which do not identify an individual User) for service improvement, which remains governed by Section 6 and our Privacy Policy.',
        ],
    },
    {
        heading: '11. Interoperability with Government Digital Public Infrastructure (DPI)',
        paragraphs: [
            'Where the Service integrates with government education Digital Public Infrastructure (including APAAR, NDEAR, the Academic Bank of Credits, or DigiLocker):',
        ],
        list: [
            'Use of DPI-linked features (e.g., linking an APAAR ID, importing/exporting academic records) is optional unless expressly stated to be a mandatory part of a specific feature, and is subject to separate consent as described in our Privacy Policy.',
            'Bodhan AI acts only as an intermediary/interface with such government systems and is not responsible for the availability, accuracy, or downtime of any third-party government DPI system.',
            'Any Aadhaar-based authentication used to access DPI-linked features is subject to the Aadhaar Act, 2016 and applicable UIDAI regulations, independent of these Terms, and will only be offered if and to the extent Bodhan AI is authorised under applicable law to perform such authentication.',
            'You represent that any Government ID Data (e.g., APAAR ID) you submit belongs to you (or, for a child User, to that child, submitted with parental consent) and is accurate.',
        ],
    },
    {
        heading: '12. Mobile Application Terms',
        paragraphs: [
            'Where you access the Service via our mobile application, the following additional terms apply:',
        ],
        list: [
            'Your download, installation, and use of the mobile application is also subject to the terms of service of the Google Play Store and/or Apple App Store, as applicable, and any conflict between those terms and these Terms shall be resolved in favour of the platform terms only to the extent required for the application to remain compliant with that platform.',
            'You must grant only those device permissions you are comfortable with; some features may not function without specific permissions (e.g., microphone access for voice-based tutoring).',
            'You consent to receive push notifications relating to the Service, which you may disable at any time through your device settings.',
        ],
    },
    {
        heading: '13. Third-Party Services',
        paragraphs: [
            'The Service may integrate or link to third-party services (e.g., payment processors, AI model providers, video-conferencing tools, government DPI systems). We are not responsible for the content, policies, or practices of third-party services, and your use of them is subject to their respective terms.',
        ],
    },
    {
        heading: '14. Disclaimers',
        paragraphs: [
            'THE SERVICE IS PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS, WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, OR NON-INFRINGEMENT, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW.',
            'We do not guarantee that the Service will be uninterrupted, error-free, or that AI-generated content will be free of inaccuracies. We do not guarantee any particular academic outcome, grade, or examination result from use of the Service, nor the continued availability or accuracy of any linked government DPI system.',
        ],
    },
    {
        heading: '15. Limitation of Liability',
        paragraphs: [
            'TO THE MAXIMUM EXTENT PERMITTED BY LAW, BODHAN AI, ITS DIRECTORS, EMPLOYEES, AND AFFILIATES SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING OUT OF OR RELATED TO YOUR USE OF THE SERVICE. OUR AGGREGATE LIABILITY FOR ANY CLAIM ARISING OUT OF THESE TERMS SHALL NOT EXCEED THE AMOUNT PAID BY YOU (IF ANY) FOR THE SERVICE IN THE [twelve (12)] MONTHS PRECEDING THE CLAIM.',
            'Nothing in these Terms limits liability that cannot be excluded or limited under applicable law, including liability arising from gross negligence, wilful misconduct, or fraud.',
        ],
    },
    {
        heading: '16. Indemnification',
        paragraphs: [
            'You agree to indemnify and hold harmless Bodhan AI, its directors, officers, employees, and agents from any claims, liabilities, damages, and expenses (including reasonable legal fees) arising out of your breach of these Terms, misuse of the Service, or violation of applicable law or third-party rights.',
        ],
    },
    {
        heading: '17. Suspension and Termination',
        paragraphs: [
            'We may suspend or terminate your access to the Service, with or without notice, if we reasonably believe you have violated these Terms, engaged in fraudulent or harmful activity, or if required by law. You may stop using the Service and request account deletion at any time by contacting us at the details in Section 21.',
            'Provisions that by their nature should survive termination (including Sections 6–10, 14, 15, and 16) shall survive.',
        ],
    },
    {
        heading: '18. Modifications to the Service and Terms',
        paragraphs: [
            'We may modify, suspend, or discontinue any part of the Service at any time. We may also revise these Terms from time to time; material changes will be notified through the Service or via email, and the “Last Updated” date will be revised. Continued use of the Service after such changes constitutes acceptance of the revised Terms.',
        ],
    },
    {
        heading: '19. Governing Law and Dispute Resolution',
        paragraphs: [
            'These Terms shall be governed by and construed in accordance with the laws of India. Subject to the paragraph below, any dispute arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts at Chennai, India.',
            'Any dispute may be referred to arbitration under the Arbitration and Conciliation Act, 1996, before a sole arbitrator appointed by mutual consent, with the seat and venue of arbitration at Chennai and proceedings conducted in English.',
        ],
    },
    {
        heading: '20. Grievance Redressal',
        paragraphs: [
            'In accordance with the Information Technology Act, 2000 and rules made thereunder, and applicable consumer protection law, grievances relating to the Service may be addressed to the Grievance Officer:',
        ],
        list: [
            'Name: Grievance Officer',
            'Email: grievance@bodhan.ai',
            'Address: IIT Madras Research Park, E1-14, 1st Floor, Kanagam Rd, Taramani, Chennai–600113',
        ],
        trailingParagraphs: [
            'Grievances will be acknowledged and resolved within the timelines prescribed under applicable law.',
        ],
    },
    {
        heading: '21. Contact Us',
        paragraphs: [
            'For questions about these Terms, please contact us at:',
            'support@bodhan.ai',
        ],
    },
    {
        heading: '22. Miscellaneous',
        list: [
            'Entire Agreement: These Terms, together with the Privacy Policy and any other policies referenced herein (and, for Institutional Users, any separate institutional agreement), constitute the entire agreement between you and Bodhan AI regarding the Service.',
            'Severability: If any provision of these Terms is held invalid or unenforceable, the remaining provisions shall continue in full force and effect.',
            'No Waiver: Failure to enforce any provision of these Terms shall not constitute a waiver of that provision.',
            'Assignment: You may not assign or transfer these Terms without our prior written consent; we may assign these Terms in connection with a merger, acquisition, or sale of assets.',
            'Force Majeure: We shall not be liable for any failure or delay in performance resulting from causes beyond our reasonable control, including outages or unavailability of third-party government DPI systems.',
        ],
    },
];

const EMAIL_REGEX = /([\w.+-]+@[\w-]+(?:\.[\w-]+)+)/g;

const linkifyEmails = (text) =>
    typeof text === 'string'
        ? text.split(EMAIL_REGEX).map((part, i) =>
              i % 2 === 1 ? (
                  <a
                      key={i}
                      href={`mailto:${part}`}
                      className="text-[var(--text-orange-500)] hover:underline"
                  >
                      {part}
                  </a>
              ) : (
                  part
              )
          )
        : text;

const Paragraphs = ({ items }) =>
    items.map((text, i) => (
        <p key={i} className="text-gray-600 text-base leading-relaxed mb-4 last:mb-0">
            {linkifyEmails(text)}
        </p>
    ));

const List = ({ items }) => (
    <ul className="space-y-3 my-4">
        {items.map((text, i) => (
            <li key={i} className="flex gap-3 text-gray-600 text-base leading-relaxed">
                <span className="w-1.5 h-1.5 rounded-full bg-[var(--text-orange-500)] flex-shrink-0 mt-2.5" />
                <span>{linkifyEmails(text)}</span>
            </li>
        ))}
    </ul>
);

const TermsAndConditionsPage = () => {
    useEffect(() => {
        window.scrollTo(0, 0);
    }, []);

    return (
        <div className="min-h-screen bg-[var(--bg-cream-50)]">
            <Navbar />

            <div className="pt-10 md:pt-16 pb-16 md:pb-24 px-4 md:px-6">
                <div className="max-w-4xl mx-auto">
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.6 }}
                        className="text-center mb-10 md:mb-14"
                    >
                        <h1 className="text-3xl md:text-5xl font-semibold text-[#1A1A1A] mb-3 md:mb-4">
                            Terms of <span className="text-[var(--text-orange-500)]">Use</span>
                        </h1>
                    </motion.div>

                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.5, delay: 0.15 }}
                        className="bg-white rounded-2xl border border-gray-100 shadow-sm p-6 md:p-12"
                    >
                        {sections.map((section, idx) => (
                            <div key={section.heading} className={idx > 0 ? 'mt-10' : ''}>
                                <h2 className="text-xl md:text-2xl font-semibold text-[#1A1A1A] mb-4">
                                    {section.heading}
                                </h2>

                                {section.paragraphs && <Paragraphs items={section.paragraphs} />}
                                {section.list && <List items={section.list} />}
                                {section.trailingParagraphs && (
                                    <Paragraphs items={section.trailingParagraphs} />
                                )}

                                {section.subsections?.map((sub) => (
                                    <div key={sub.subheading} className="mt-6">
                                        <h3 className="text-lg font-semibold text-[#1A1A1A] mb-3">
                                            {sub.subheading}
                                        </h3>
                                        {sub.paragraphs && <Paragraphs items={sub.paragraphs} />}
                                        {sub.list && <List items={sub.list} />}
                                    </div>
                                ))}
                            </div>
                        ))}
                    </motion.div>
                </div>
            </div>

            <Footer />
        </div>
    );
};

export default TermsAndConditionsPage;
